// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OgrenciKursYonetimi.Web.Data;

#nullable disable

namespace OgrenciKursYonetimi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250424190142_FixKayitNaming")]
    partial class FixKayitNaming
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.Kurs", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KursId"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("KursId");

                    b.ToTable("Kurslar");
                });

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.KursKayit", b =>
                {
                    b.Property<int>("KayitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KayitId"));

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KursId")
                        .HasColumnType("integer");

                    b.Property<int?>("KursKayitKayitId")
                        .HasColumnType("integer");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("integer");

                    b.HasKey("KayitId");

                    b.HasIndex("KursId");

                    b.HasIndex("KursKayitKayitId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("KursKayitlar");
                });

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OgrenciId"));

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OgrenciAd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OgrenciSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OgrenciId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.KursKayit", b =>
                {
                    b.HasOne("OgrenciKursYonetimi.Web.Data.Kurs", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciKursYonetimi.Web.Data.KursKayit", null)
                        .WithMany("KursKayitlari")
                        .HasForeignKey("KursKayitKayitId");

                    b.HasOne("OgrenciKursYonetimi.Web.Data.Ogrenci", "Ogrenci")
                        .WithMany("KursKayitlari")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.KursKayit", b =>
                {
                    b.Navigation("KursKayitlari");
                });

            modelBuilder.Entity("OgrenciKursYonetimi.Web.Data.Ogrenci", b =>
                {
                    b.Navigation("KursKayitlari");
                });
#pragma warning restore 612, 618
        }
    }
}
